version: "3"
services:
  # user_service:
  #   build: .
  #   links:
  #     - user_db
  #   command: yarn start
  #   hostname: user_service_in_container
  #   volumes:
  #     - ./:/app
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "4000:4000"

  # user_db:
  #   image: 'mongo:3.4.1'
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - "/tmp/db:/data/db"
  #   restart: always
  db:
    image:  mysql:5.6
    restart: always
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 888888
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
  adminer:
    image:  adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  db-data:
